#!/usr/bin/env node

/**    
 *   @licstart  The following is the entire license notice for the 
 *   JavaScript code in this page.
 *
 *   Copyright (C) 2015  Ewan Valentine
 *
 *   The JavaScript code in this page is free software: you can
 *   redistribute it and/or modify it under the terms of the GNU
 *   General Public License (GNU GPL) as published by the Free Software
 *   Foundation, either version 3 of the License, or (at your option)
 *   any later version.  The code is distributed WITHOUT ANY WARRANTY;
 *   without even the implied warranty of MERCHANTABILITY or FITNESS
 *   FOR A PARTICULAR PURPOSE.  See the GNU GPL for more details.
 *
 *   As additional permission under GNU GPL version 3 section 7, you
 *   may distribute non-source (e.g., minimized or compacted) forms of
 *   that code without the copy of the GNU GPL normally required by
 *   section 4, provided you include this license notice and a URL
 *   through which recipients can access the Corresponding Source.   
 *
 *
 *   @licend  The above is the entire license notice
 *   for the JavaScript code in this page.
 */
var exec = require('ssh-exec');
var _ = require('lodash');
var config = require('config');

var args = process.argv.slice(2);

// Foreach host entry
_.forEach(config.get('hosts'), function(host, name) {

  // If host name equals host argument
  if(name === args[0]) {

  	// Foreach command alias
    _.forEach(config.get('aliases'), function(command, alias) {

      // If alias equals command
      if(args[1] === alias) {

      	// Execute aliased command
        exec(command, host).pipe(process.stdout);
      } else {

      	// Execute raw command
        exec(args[1], host).pipe(process.stdout);
      }
    });
  }
});